const modules=[
['00','Quick Start',`<p><b>See the proof first — then understand the complete system.</b></p><p>Start with a full overview of the One Minute Formula and how every module connects from niche selection to monetization.</p><ul><li>Real dashboard and revenue proof: $1,490 earned over 300 days</li><li>Examples of faceless AI videos behind the results</li><li>Complete roadmap through all 7 modules</li><li>Why the prompts are one of the most valuable parts of the course</li></ul>`],
['01','Find Your Niche',`<p><b>Don't copy my niche. Find the one you can actually build around.</b></p><p>Your niche should match your genuine interest — because content without real curiosity gets hard to sustain.</p><ul><li>The 3 niche criteria: Stories, Emotion, and YOU</li><li>Breakdowns of True Crime, History, World News, Psychology, Mysteries & Unexplained Events</li><li>How the ChatGPT system adapts to ANY niche you choose</li><li>Action step: choose one niche and identify 5 competitor accounts</li></ul>`],
['02','The Script System · MASTER PROMPT',`<p><b>The core module. Everything starts with the script.</b></p><p>You get the exact ChatGPT Master Prompt used to build cinematic short-form stories — designed to adapt to your niche, topic and character style.</p><ul><li>Set the 3 variables: NICHE, TOPIC, CHARACTER STYLE</li><li>Generate a complete cinematic short-form script</li><li>Turn script phrases into image prompts for Flow</li><li>Learn how to tweak the output when something feels off</li><li><b>Download the full Gamer Kitty Master Prompt on day one</b></li></ul><p class="module-task">TASK → Generate your first script + image prompts for the first 3 phrases.</p>`],
['03','AI Production',`<p><b>This is where your video comes to life.</b></p><p>Build your narrator or character, define a visual identity, then move through the full 4-tool production stack.</p><ul><li>Flow → generate cinematic images from your prompts</li><li>Grok → animate every image</li><li>ElevenLabs → create professional voiceover</li><li>CapCut → assemble clips, subtitles, music and export</li><li>Practical editing guidance: clip length, fonts, music levels and key-moment effects</li></ul><p class="module-task">TASK → Complete and export your first full video.</p>`],
['04','Launch & Grow',`<p><b>Your video is ready. Now publish it the right way.</b></p><ul><li>When to post using the included global timing table</li><li>How often to post without sacrificing quality</li><li>Ready-to-adapt description template</li><li>Hashtag strategy for your topic and niche</li><li>What to track: watch time, view trend, comments and shares</li><li>Included resource: Best Posting Time guide</li></ul><p class="module-task">TASK → Post your first video, wait 24 hours and review the analytics.</p>`],
['05','Make Money',`<p><b>Turn the content you're already making into multiple income paths.</b></p><ul><li>TikTok Creator Rewards — requirements and real account examples</li><li>YouTube Shorts — repurpose the same video for another revenue stream</li><li>TikTok Shop — choose products that genuinely match your niche</li><li>How to protect audience trust while monetizing</li></ul><p class="module-task">TASK → Check Creator Rewards, create a YouTube channel and identify 3 niche-relevant products.</p>`],
['06','Full Workflow',`<p><b>No theory. No slides. One real video built from absolute zero.</b></p><p>Watch the entire process recorded in real time in a completely different niche, proving the workflow isn't limited to gaming.</p><ul><li>ChatGPT → Prompt → Script → Image prompts</li><li>Flow → Image prompts → Cinematic visuals</li><li>Grok → Static images → Animated clips</li><li>ElevenLabs → Script → Professional voiceover</li><li>CapCut → Everything → Finished video</li><li>Then watch the finished video get posted using the Module 4 timing strategy</li></ul><p class="module-task">After this module, you have the complete workflow to run the system yourself.</p>`]
];
document.querySelector('#modules').innerHTML=modules.map(m=>`<div class="module"><button><span class="num">MODULE ${m[0]}</span><b>${m[1]}</b><span class="plus">+</span></button><div class="detail">${m[2]}</div></div>`).join('');
document.querySelectorAll('.module button').forEach(b=>b.onclick=()=>{const m=b.parentElement;m.classList.toggle('open');b.querySelector('.plus').textContent=m.classList.contains('open')?'−':'+'});
const reviews=["the course was very well written and understandable.","good, veeery good 😇","one of my favourite creators! thank you so much for your product, saved me a lot of time and money 😍🙌","the best purchase of my life gng ✌🏼","love it! thank you <3","There is everything you need to know in this course, everything is understandable and very well put together, overall Im not disappointed :)","OMG! It’s been only a few weeks after I started posting on my account and I already started blowing 😍🔥 The course is banger, thank you Kitty!!! 💗","amazing course, amazing creator, amazing everything 💗 Definitely recommend for everyone who wants to make some bread, I’m on my way 😍","Peak! 😭🔥🔥🔥 All information is presented as clearly and efficiently as possible! I recommend it to everyone, for such a price it is a gift 🔥 Thank you Gamer Kitty!"];
function reviewCards(arr){const x=arr.map(r=>`<article class="review"><div class="stars">★★★★★</div><p>“${r}”</p><small>Verified buyer ✓</small></article>`).join('');return x+x}
document.querySelector('#track1').innerHTML=reviewCards(reviews.slice(0,5));document.querySelector('#track2').innerHTML=reviewCards(reviews.slice(4));
const faqs=[['Do I need editing experience?','No. The course walks you through the workflow step by step, including CapCut production and the creator assets used to speed things up.'],['Do I need to show my face?','No. The system is designed for faceless short-form content. You create a narrator or character and build a consistent visual identity around your channel.'],['What exactly is the Master Prompt?','It is the full AI instruction system used to generate cinematic short-form storytelling and image prompts. You customize the niche, topic and character style, so the workflow can adapt to the content you want to make.'],['Is this only for gaming content?','No. Gaming is Gamer Kitty’s own niche and proof of the system, not a requirement. Module 1 helps you choose YOUR niche, and the Master Prompt is built around variables for niche, topic and character style. The full-workflow module even demonstrates the process outside gaming.'],['What niches can I create in?','The course discusses examples including True Crime, History, World News, Psychology, Mysteries & Unexplained Events — but the system is designed to adapt beyond those examples too.'],['Do I get instant access?','Yes — access is delivered through Gumroad after purchase.'],['How does the 90-Day Guarantee work?','You must complete the course, consistently apply the system and provide evidence of publishing during the 90-day period. Final eligibility follows the published Guarantee Terms.']];
document.querySelector('#faqs').innerHTML=faqs.map(f=>`<div class="faq-item"><button class="faq-q">${f[0]}<span>+</span></button><div class="faq-a">${f[1]}</div></div>`).join('');document.querySelectorAll('.faq-q').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
const modal=document.querySelector('#modal'),body=document.querySelector('#modalBody');document.querySelector('.close').onclick=()=>modal.close();
const STARTER_PACK_URL='assets/Gamer-Kitty-Viral-Short-Form-Starter-Pack.pdf';
const EMAILOCTOPUS_FORM_ID='fa0e1b04-c038-11f1-b83d-8795b2d6c401';
const EMAILOCTOPUS_FORM_SRC='https://eomail5.com/form/fa0e1b04-c038-11f1-b83d-8795b2d6c401.js';
function mountEmailOctopusForm(){
  const host=document.querySelector('#emailOctopusHost');
  if(!host)return;
  const script=document.createElement('script');
  script.async=true;
  script.src=EMAILOCTOPUS_FORM_SRC;
  script.dataset.form=EMAILOCTOPUS_FORM_ID;
  host.appendChild(script);
}
document.querySelector('#freeBtn').onclick=()=>{
  body.innerHTML=`<div class="eyebrow">FREE · $0</div><h3>Get the Viral Short-Form Starter Pack</h3><p class="modal-lead">Enter your email and get the 8-page Gamer Kitty starter system. You'll also receive a short follow-up series with creator tips and the One Minute Formula offer. Unsubscribe anytime.</p><div id="emailOctopusHost" class="emailoctopus-host"><div class="form-loading">Loading secure signup…</div></div><div class="mini-includes"><span>10 HOOKS</span><span>60-SEC BLUEPRINT</span><span>MINI AI PROMPT</span><span>CHECKLIST + CTAs</span></div><p class="delivery-note">Your Starter Pack will be sent to the email address you subscribe with.</p>`;
  modal.showModal();
  mountEmailOctopusForm();
};
const guaranteeHTML=`<div class="eyebrow">90-DAY MONETIZATION GUARANTEE</div><h3>Guarantee Terms — Launch Draft</h3><p class="modal-lead">The guarantee is designed for students who actually complete and apply the system. These terms should be reviewed before the public launch.</p><div class="terms-grid"><p><b>90-day period</b><br>The period begins on the original purchase date.</p><p><b>Course completion</b><br>Complete all seven course modules and the included Full Workflow.</p><p><b>Consistent publishing</b><br>Publish at least 30 original short-form videos created using the course workflow during the 90-day period.</p><p><b>What counts as monetization</b><br>Acceptance into, or earnings from, an eligible creator monetization path covered in the course, such as a platform creator-rewards program, YouTube monetization, or niche-relevant commerce/affiliate income.</p><p><b>Evidence</b><br>Provide links or screenshots showing the published videos, account analytics and relevant monetization status.</p><p><b>Claim window</b><br>Submit the request within 7 days after the 90-day period ends.</p></div><p class="legal-note">A refund is not based on a promised income amount or view count. Platform eligibility, regional availability and third-party program rules can change and remain outside Gamer Kitty's control. Final public terms should match your Gumroad refund policy and be legally reviewed for the countries where you sell.</p>`;
function showGuarantee(){body.innerHTML=guaranteeHTML;modal.showModal()}
document.querySelector('#termsBtn').onclick=showGuarantee;
document.querySelector('#guaranteeFooterBtn').onclick=showGuarantee;
document.querySelector('#privacyBtn').onclick=()=>{body.innerHTML=`<div class="eyebrow">PRIVACY</div><h3>Privacy — Launch Draft</h3><p>If you request the free Starter Pack, your email address is submitted through EmailOctopus for delivery of the Starter Pack and related Gamer Kitty follow-up emails. You can unsubscribe using the link included in those emails.</p><p class="legal-note">This is still a launch draft, not a complete privacy policy. Before public launch, add your privacy contact details, retention information, and any other disclosures required for the way the site is actually operated.</p>`;modal.showModal()};
window.addEventListener('mousemove',e=>{if(innerWidth<850)return;const art=document.querySelector('.hero-art img');const x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*7;art.style.transform=`translate(${x}px,${y}px)`});
